JOB = CSEARCH;
DATA MAX_CONFORMERS = 500000;
DATA CPTTIME = 30;
FILE INP_FILE = "syssearch1.inp" INPUT KEEP;
FILE STATUS_FILE = "syssearch1.sta" INPUT KEEP;
FILE PROGRESS_FILE = "syssearch1.prg" OUTPUT;
FILE CPTFILE = "syssearch1.cpt" OUTPUT;
FILE ANGLE_FILE = "syssearch1.ang" OUTPUT TYPE = SEARCH_ANG;
FILE ENERGY_PARMS = "syssearch1.par";
