# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-03 18:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='username')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('work_org', models.CharField(default='', max_length=20, verbose_name='work_org')),
                ('research_dir', models.CharField(default='', max_length=20, verbose_name='research_dir')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='work_name')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='work_decs')),
                ('mol_file', models.FileField(upload_to=works.models.upload_to, verbose_name='mol_file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ADMET_prediction',
                'verbose_name_plural': 'ADMET_prediction',
            },
        ),
        migrations.CreateModel(
            name='AutoDock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='work_decs')),
                ('size_x', models.FloatField(verbose_name='size_x')),
                ('size_y', models.FloatField(verbose_name='size_y')),
                ('size_z', models.FloatField(verbose_name='size_z')),
                ('center_x', models.FloatField(verbose_name='center_x')),
                ('center_y', models.FloatField(verbose_name='center_y')),
                ('center_z', models.FloatField(verbose_name='center_z')),
                ('pdb_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='lig_file')),
                ('price', models.IntegerField(default=10000, verbose_name='price')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('out_path', models.FileField(null=True, upload_to=b'', verbose_name='out_path')),
                ('affinity', models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'dock',
                'verbose_name_plural': 'dock',
            },
        ),
        migrations.CreateModel(
            name='AutoDock2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='work_decs')),
                ('pdb_file', models.FileField(upload_to=works.models.dock2_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.dock2_upload_to, verbose_name='lig_file')),
                ('resi_file', models.FileField(upload_to=works.models.dock2_upload_to, verbose_name='resi_file')),
                ('price', models.IntegerField(default=10000, verbose_name='price')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('out_path', models.FileField(null=True, upload_to=b'', verbose_name='out_path')),
                ('affinity', models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'dock2',
                'verbose_name_plural': 'dock2',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='image')),
                ('index', models.IntegerField(verbose_name='index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('algorithm', models.CharField(choices=[('AutoDock', 'AutoDock'), ('AutoDock-vina', 'AutoDock-vina'), ('Glide', 'Glide')], max_length=20)),
                ('size_x', models.FloatField(null=True, verbose_name='size_x')),
                ('size_y', models.FloatField(null=True, verbose_name='size_y')),
                ('size_z', models.FloatField(null=True, verbose_name='size_z')),
                ('center_x', models.FloatField(null=True, verbose_name='center_x')),
                ('center_y', models.FloatField(null=True, verbose_name='center_y')),
                ('center_z', models.FloatField(null=True, verbose_name='center_z')),
                ('resn', models.CharField(max_length=100, null=True, verbose_name='resn')),
                ('pdb_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='lig_file')),
                ('reference_file', models.FileField(null=True, upload_to=works.models.dock_upload_to, verbose_name='reference_file')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('out_path', models.FileField(null=True, upload_to=b'', verbose_name='out_path')),
                ('affinity', models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'dock',
                'verbose_name_plural': 'dock',
            },
        ),
        migrations.CreateModel(
            name='Gbsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('pdb_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='lig_file')),
                ('complex_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='complex_file')),
                ('status', models.CharField(default='waiting', max_length=20, verbose_name='status')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gbsa',
                'verbose_name_plural': 'gbsa',
            },
        ),
        migrations.CreateModel(
            name='Passwordreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('screen_cat', models.CharField(max_length=10, verbose_name='screen_cat')),
                ('affinity', models.FloatField(verbose_name='affinity')),
                ('path', models.FileField(upload_to=b'', verbose_name='out_file')),
            ],
            options={
                'verbose_name': 'screen',
                'verbose_name_plural': 'screen',
            },
        ),
        migrations.CreateModel(
            name='SeaTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('smiles', models.CharField(max_length=200, verbose_name='smiles')),
                ('target', models.CharField(default='null', max_length=500, verbose_name='targets')),
            ],
            options={
                'verbose_name': 'SeaTarget',
                'verbose_name_plural': 'SeaTarget',
            },
        ),
        migrations.CreateModel(
            name='SeaVirScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('affinity', models.FloatField(verbose_name='affinity')),
                ('path', models.FileField(upload_to=b'', verbose_name='out_file')),
            ],
            options={
                'verbose_name': 'SeaVirScreen',
                'verbose_name_plural': 'SeaVirScreen',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=20, verbose_name='target_name')),
            ],
            options={
                'verbose_name': 'target_name',
                'verbose_name_plural': 'target_name',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'verifycode',
                'verbose_name_plural': 'verifycode',
            },
        ),
        migrations.CreateModel(
            name='VirScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('mol_db', models.CharField(choices=[('zinc', 'zinc'), ('chembl', 'chembl'), ('drugbank', 'drugbank'), ('chinese-medicine', 'chinese-medicine'), ('taosu', 'taosu'), ('bailingwei', 'bailingwei'), ('jianqiao', 'jianqiao')], max_length=20, null=True, verbose_name='mol_db')),
                ('target', models.CharField(max_length=100, null=True, verbose_name='target')),
                ('smiles', models.CharField(max_length=200, null=True, verbose_name='smiles')),
                ('pdb_file', models.FileField(null=True, upload_to=works.models.screen_upload_to, verbose_name='pdb_file')),
                ('resn', models.CharField(max_length=100, null=True, verbose_name='resn')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('email', models.CharField(default='', max_length=100, verbose_name='email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'VirScreen',
                'verbose_name_plural': 'VirScreen',
            },
        ),
        migrations.CreateModel(
            name='VirtualScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='work_decs')),
                ('size_x', models.FloatField(verbose_name='size_x')),
                ('size_y', models.FloatField(verbose_name='size_y')),
                ('size_z', models.FloatField(verbose_name='size_z')),
                ('center_x', models.FloatField(verbose_name='center_x')),
                ('center_y', models.FloatField(verbose_name='center_y')),
                ('center_z', models.FloatField(verbose_name='center_z')),
                ('target', models.CharField(default='', max_length=100000, verbose_name='target')),
                ('pdb_file', models.FileField(upload_to=works.models.screen_upload_to, verbose_name='pdb_file')),
                ('user_db', models.FileField(null=True, upload_to=works.models.screen_upload_to, verbose_name='user_db')),
                ('price', models.IntegerField(default=10000, verbose_name='price')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'virtualscreen',
                'verbose_name_plural': 'virtualscreen',
            },
        ),
        migrations.CreateModel(
            name='VirtualScreen2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='work_decs')),
                ('target', models.CharField(default='', max_length=100000, verbose_name='target')),
                ('pdb_file', models.FileField(upload_to=works.models.screen2_upload_to, verbose_name='pdb_file')),
                ('resi_file', models.FileField(upload_to=works.models.screen2_upload_to, verbose_name='resi_file')),
                ('user_db', models.FileField(null=True, upload_to=works.models.screen2_upload_to, verbose_name='user_db')),
                ('price', models.IntegerField(default=10000, verbose_name='price')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'virtualscreen2',
                'verbose_name_plural': 'virtualscreen2',
            },
        ),
    ]
